language: ruby
sudo: true
cache: bundler

branches:
  except:
    - gh-pages

rvm:
  - 2.0.0
  - 2.4.0
  - ruby-head

bundler_args: --without production

before_install:
  - phantomjs --version

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

  - bundle exec rake travis

script:
  #- bundle exec rake test:posts
  - cd _tests
  - bundle exec cucumber

notifications:
  email: false
